(ns doc
  (:require
   [babashka.fs :as fs]
   [babashka.process :refer [shell]]
   [clojure.string :as str]))

(def output-path "docs")

;; Would it be useful to wrap following into a library?
(try
  (shell "tbls --dsn sqlite:./Chinook_Sqlite.sqlite doc --rm-dist")
         ;; Uncomment to use Mermaid for diagrams:
         ; "--er-format" "mermaid")
  (catch java.io.IOException e
    (println "Something went wrong:")
    (println (ex-message e))
    (println)
    (println "Please make sure you have `tbls` program installed.")))
;; tbls seems to have `docPath` option to use different output path than `dbdoc`.
;; But it seems to be only available when using yaml config but not passable via CLI,
;; so let's move the output dir ourselves afterwards.
(fs/delete-tree output-path)
(fs/move "dbdoc" output-path)

(fs/update-file
 (str output-path "/README.md")
 #(str "---\nsidebar_position: 0\n---\n\n" %))

;; Strip out distracting tbls footer, credits are in the readme
(doseq [file (fs/glob output-path "*.md")]
  (fs/update-file
   (fs/file file)
   str/replace "---\n\n> Generated by [tbls](https://github.com/k1LoW/tbls)" ""))
